language: java
sudo: false
before_install:
- wget https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.2.1004.zip
- unzip SimbaJDBCDriverforGoogleBigQuery42_1.2.2.1004.zip
- mvn install:install-file -Dfile=GoogleBigQueryJDBC42.jar -DgroupId=com.simba.googlebigquery -DartifactId=googlebigquery-jdbc42 -Dversion=1.2.2.1004 -Dpackaging=jar -DgeneratePom=true
- cd bigquery-driver-shade && mvn clean install -DskipTests
script:
- mvn clean install -DskipTests
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UBxFLvA8U1pJoOYEMuXafj1EmmqyH3RGrRKPY0ADJIdSIUrEW5/zGGSYWQIY9EqYMs4FgBc9SnC1n+P8fGfvnMgP7s6XIuvRhybMPYbcquXUasLID2TU5GzNc8N+gvjhxHtEc8OgFfDaE1b1pL79bIYS99vDZ8pcjYOdf1i3ND3HkHTJPROP9bdWLflGAjaz/RW0ROZYqpEyH6gPTymOxkCXrarX2pngRSGlSEZkQoKLwfzuwZKeoF4fBd3eJ74K1SqTPmOSaYp2VR04Pfq+JwjFEje0oh1vN3Svty1bPNDwNVDpyG/EhifNCInPyM/3U7Gaqm2b0miX3pwz0PvENHtDHmiAh/FyrH39CD144gHXfC75PzOeNlAVkO2T5h2OpzGLHB+YlUt2z+QHt7bjK2UYeLwzYqHFz1S25sQzDGwP8iSrQNlvY8wfIyLWuFaFVRG5bHWBfsKYfjHRQ4H4m0MupMr9A71JncKE+5ZiD3fQejtSwOVojHKvt7nIinawCS5aH0DAf84WO0WTZ6ZsSe28PwCYAzYUk8gUiRDgTw3jnL5gupLXfUMyIAs1hB+jDfTun3BZnWj8pVQRMcnWfNgB9ib0BBnlEwE8puDCOITplrOf19KP3RABZZQT2zZR4Xto5j6B3j9/KZ8uLNh33d4tWheegFQMxj3PSQSsgrI=
  file_glob: true
  file: target/dremio-bigquery-plugin-*.jar
  on:
    repo: panoramichq/dremio-bigquery-connector
