language: java
sudo: false
before_install:
- wget https://maven.dremio.com/free/com/dremio/distribution/dremio-jdbc-driver/4.0.0-201909121834570395-c7a5071/dremio-jdbc-driver-4.0.0-201909121834570395-c7a5071.jar
  -P src/main/resources
- wget https://a1.panocdn.com/support_files/dremio-oss/GoogleBigQueryJDBC42_1.2.2.1004.jar
script:
- mvn install:install-file -Dfile=GoogleBigQueryJDBC42.jar -DgroupId=com.simba.googlebigquery -DartifactId=googlebigquery-jdbc42 -Dversion=1.2.2.1004 -Dpackaging=jar -DgeneratePom=true
- cd bigquery-driver-shade && mvn clean install && cd ..
- mvn clean install -DskipTests
- mv target/dremio-bigquery-plugin-*.jar dremio-bigquery-plugin.jar
deploy:
  provider: releases
  api_key:
    secure: UBxFLvA8U1pJoOYEMuXafj1EmmqyH3RGrRKPY0ADJIdSIUrEW5/zGGSYWQIY9EqYMs4FgBc9SnC1n+P8fGfvnMgP7s6XIuvRhybMPYbcquXUasLID2TU5GzNc8N+gvjhxHtEc8OgFfDaE1b1pL79bIYS99vDZ8pcjYOdf1i3ND3HkHTJPROP9bdWLflGAjaz/RW0ROZYqpEyH6gPTymOxkCXrarX2pngRSGlSEZkQoKLwfzuwZKeoF4fBd3eJ74K1SqTPmOSaYp2VR04Pfq+JwjFEje0oh1vN3Svty1bPNDwNVDpyG/EhifNCInPyM/3U7Gaqm2b0miX3pwz0PvENHtDHmiAh/FyrH39CD144gHXfC75PzOeNlAVkO2T5h2OpzGLHB+YlUt2z+QHt7bjK2UYeLwzYqHFz1S25sQzDGwP8iSrQNlvY8wfIyLWuFaFVRG5bHWBfsKYfjHRQ4H4m0MupMr9A71JncKE+5ZiD3fQejtSwOVojHKvt7nIinawCS5aH0DAf84WO0WTZ6ZsSe28PwCYAzYUk8gUiRDgTw3jnL5gupLXfUMyIAs1hB+jDfTun3BZnWj8pVQRMcnWfNgB9ib0BBnlEwE8puDCOITplrOf19KP3RABZZQT2zZR4Xto5j6B3j9/KZ8uLNh33d4tWheegFQMxj3PSQSsgrI=
  file: dremio-bigquery-plugin.jar
  on:
    repo: panoramichq/dremio-bigquery-connector
